name: Deploy Dev Preview

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web for dev
        run: flutter build web --release --base-href="/wedding-for-you/"

      - name: Remove custom domain (CNAME) for dev
        run: rm -f build/web/CNAME

      - name: Deploy to GitHub Pages (Dev)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages-dev
